# Generated by Django 2.0.6 on 2018-06-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('package', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('manager', models.CharField(max_length=50)),
                ('coin', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
