# Generated by Django 2.0.5 on 2018-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0003_auto_20180629_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='package',
            field=models.CharField(choices=[('All', 'All'), ('Ultimate Executive', 'Ultimate Executive'), ('Ultimate', 'Ultimate'), ('Bitcoin Blast', 'Bitcoin Blast')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
