# Generated by Django 2.0.5 on 2018-07-03 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0004_coupon_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 9, 43, 8, 505391)),
        ),
    ]
