# Generated by Django 2.0.5 on 2018-07-03 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0005_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.AddField(
            model_name='history',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 9, 47, 55, 995507)),
        ),
    ]
