# Generated by Django 2.0.5 on 2018-07-03 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0006_auto_20180703_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 10, 42, 36, 539663, tzinfo=utc)),
        ),
    ]
