# Generated by Django 2.0.5 on 2018-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinpayment', '0009_auto_20180703_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
